In [2]:
import numpy as np

In [4]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])

In [6]:
mean_a = np.array(a.mean(axis=0))

In [9]:
mean_a

array([2. , 8.4])

In [10]:
a_centered = np.array(a-mean_a)

In [11]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [23]:
a_centered_sp = np.transpose(a_centered[:,:1]) @ np.transpose(a_centered[:,1:]
a_centered_sp

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 5)

In [29]:
np.transpose(a_centered[:,1:])

array([[-2.4, -0.4,  2.6,  1.6, -1.4]])

In [28]:
np.transpose(a_centered[:,:1])

array([[-1.,  0.,  1.,  1., -1.]])